tasks:
  tv task:
    rss: $rssFeed
    all_series: yes
    transmission:
      host: localhost
      port: 9091
      addpaused: No
      ratio: 0
    clean_transmission:
      host: localhost
      port: 9091
      finished_for: 2 days
      directories:
        - \A/+data/+apps/+torrent/+complete(\Z|/+.*)
